spring:
  application:
    name: customers
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

cep:
  api:
    base-url: https://viacep.com.br/ws

server:
  servlet:
    session:
      timeout: 7200s
