CREATE TABLE customers (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    document     VARCHAR(14)  NOT NULL,
    phone        VARCHAR(15)  NOT NULL,
    zip_code     VARCHAR(9)   NOT NULL,
    street       VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL,
    city         VARCHAR(255) NOT NULL,
    state        CHAR(2)      NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT customers_email_unique    UNIQUE (email),
    CONSTRAINT customers_document_unique UNIQUE (document)
);
